SET FOREIGN_KEY_CHECKS=0;
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (186, '2A', 2020, 25, 1, 244, cent);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (244, 'Wahab', 'Razma', 'razma.wahab@edu.sigtuna.se', 'cent', 4, 1, 6);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (187, '2B', 2020, 25, 1, 245, cent);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (245, 'Anna', 'von Zweigbergk', 'anna.von@edu.sigtuna.se', 'cent', 4, 1, 6);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (188, '2A', 2020, 23, 1, 246, edda);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (246, 'Lorraine', 'Abdallah', 'lorraine.abdallah@edu.sigtuna.se', 'edda', 4, 1, 6);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (189, '2B', 2020, 25, 1, 247, edda);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (247, 'Ana', 'Lazo Almgren', 'ana.lazo@edu.sigtuna.se', 'edda', 4, 1, 6);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (190, '2A', 2020, 27, 1, 172, gala);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (191, '2B', 2020, 28, 1, 248, gala);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (248, 'Suzanne', 'Flemström', 'suzanne.flemstrom@edu.sigtuna.se', 'gala', 4, 1, 6);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (192, '2A', 2020, 28, 1, 249, norr);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (249, 'Charlotte', 'Leetmaa', 'charlotte.leetmaa@edu.sigtuna.se', 'norr', 4, 1, 6);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (193, '2B', 2020, 27, 1, 250, norr);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (250, 'Hero', 'Sadek', 'hero.sadek@edu.sigtuna.se', 'norr', 4, 1, 6);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (194, '2', 2020, 19, 1, 251, oden);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (251, 'Josephine', 'Almesjö', 'josephine.almesjo@edu.sigtuna.se', 'oden', 4, 1, 6);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (195, '2', 2020, 18, 1, 181, rabg);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (196, '2G', 2020, 24, 1, 252, saga);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (252, 'Susanna', 'Carlsson', 'susanna.carlsson@edu.sigtuna.se', 'saga', 4, 1, 6);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (197, '2R', 2020, 24, 1, 253, saga);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (253, 'Zaira', 'Hussein', 'zaira.h.hussein@edu.sigtuna.se', 'saga', 4, 1, 6);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (198, '2', 2020, 23, 1, 254, skep);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (254, 'Kristina', 'Andersen', 'kristina.andersen@edu.sigtuna.se', 'skep', 4, 1, 6);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (199, '2A', 2020, 22, 1, 255, pers);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (255, 'Anna-Karin', 'Eriksson Härtell', 'annakarin.eriksson@edu.sigtuna.se', 'pers', 4, 1, 6);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (200, '2B', 2020, 20, 1, 56, pers);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (201, '2C', 2020, 19, 1, 256, pers);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (256, 'Johanna', 'Matsson', 'johanna.matsson@edu.sigtuna.se', 'pers', 4, 1, 6);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (202, '2A', 2020, 22, 1, 257, gert);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (257, 'Mikaela', 'Appellund', 'mikaela.appellund@edu.sigtuna.se', 'gert', 4, 1, 6);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (203, '2B', 2020, 23, 1, 258, gert);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (258, 'Ulrika', 'Lindmark-Rehn', 'ulrika.rehn@edu.sigtuna.se', 'gert', 4, 1, 6);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (204, '2A', 2020, 21, 1, 259, shoj);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (259, 'Marie', 'Haglund', 'marie.haglund@edu.sigtuna.se', 'shoj', 4, 1, 6);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (205, '2B', 2020, 20, 1, 260, shoj);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (260, 'Ida Maria', 'Rudin', 'ida.rudin@edu.sigtuna.se', 'shoj', 4, 1, 6);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (206, '2A', 2020, 26, 1, 261, satu);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (261, 'Nusin', 'Grama', 'nusin.grama@edu.sigtuna.se', 'satu', 4, 1, 6);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (207, '2B', 2020, 26, 1, 262, satu);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (262, 'Mona', 'Dirawi', 'mona.dirawi@edu.sigtuna.se', 'satu', 4, 1, 6);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (208, '2A', 2020, 21, 1, 263, ting);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (263, 'Linda', 'Lindroos', 'linda.lindroos@edu.sigtuna.se', 'ting', 4, 1, 6);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (209, '2B', 2020, 20, 1, 264, ting);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (264, 'Jessica', 'Sundberg', 'jessica.sundberg@edu.sigtuna.se', 'ting', 4, 1, 6);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (210, '2', 2020, 34, 1, NULL, vari);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (211, '2', 2020, None, 1, 265, jose);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (265, 'Ewa', 'Andersson', 'ewa.andersson@josefinaskolan.nu', 'jose', 4, 1, 6);
SET FOREIGN_KEY_CHECKS=0;
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (186, '2A', 2020, 25, 1, 244, cent);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (244, 'Wahab', 'Razma', 'razma.wahab@edu.sigtuna.se', 'cent', 4, 1, 6);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (187, '2B', 2020, 25, 1, 245, cent);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (245, 'Anna', 'von Zweigbergk', 'anna.von@edu.sigtuna.se', 'cent', 4, 1, 6);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (188, '2A', 2020, 23, 1, 246, edda);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (246, 'Lorraine', 'Abdallah', 'lorraine.abdallah@edu.sigtuna.se', 'edda', 4, 1, 6);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (189, '2B', 2020, 25, 1, 247, edda);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (247, 'Ana', 'Lazo Almgren', 'ana.lazo@edu.sigtuna.se', 'edda', 4, 1, 6);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (190, '2A', 2020, 27, 1, 172, gala);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (191, '2B', 2020, 28, 1, 248, gala);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (248, 'Suzanne', 'Flemström', 'suzanne.flemstrom@edu.sigtuna.se', 'gala', 4, 1, 6);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (192, '2A', 2020, 28, 1, 249, norr);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (249, 'Charlotte', 'Leetmaa', 'charlotte.leetmaa@edu.sigtuna.se', 'norr', 4, 1, 6);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (193, '2B', 2020, 27, 1, 250, norr);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (250, 'Hero', 'Sadek', 'hero.sadek@edu.sigtuna.se', 'norr', 4, 1, 6);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (194, '2', 2020, 19, 1, 251, oden);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (251, 'Josephine', 'Almesjö', 'josephine.almesjo@edu.sigtuna.se', 'oden', 4, 1, 6);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (195, '2', 2020, 18, 1, 181, rabg);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (196, '2G', 2020, 24, 1, 252, saga);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (252, 'Susanna', 'Carlsson', 'susanna.carlsson@edu.sigtuna.se', 'saga', 4, 1, 6);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (197, '2R', 2020, 24, 1, 253, saga);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (253, 'Zaira', 'Hussein', 'zaira.h.hussein@edu.sigtuna.se', 'saga', 4, 1, 6);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (198, '2', 2020, 23, 1, 254, skep);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (254, 'Kristina', 'Andersen', 'kristina.andersen@edu.sigtuna.se', 'skep', 4, 1, 6);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (199, '2A', 2020, 22, 1, 255, pers);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (255, 'Anna-Karin', 'Eriksson Härtell', 'annakarin.eriksson@edu.sigtuna.se', 'pers', 4, 1, 6);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (200, '2B', 2020, 20, 1, 56, pers);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (201, '2C', 2020, 19, 1, 256, pers);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (256, 'Johanna', 'Matsson', 'johanna.matsson@edu.sigtuna.se', 'pers', 4, 1, 6);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (202, '2A', 2020, 22, 1, 257, gert);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (257, 'Mikaela', 'Appellund', 'mikaela.appellund@edu.sigtuna.se', 'gert', 4, 1, 6);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (203, '2B', 2020, 23, 1, 258, gert);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (258, 'Ulrika', 'Lindmark-Rehn', 'ulrika.rehn@edu.sigtuna.se', 'gert', 4, 1, 6);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (204, '2A', 2020, 21, 1, 259, shoj);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (259, 'Marie', 'Haglund', 'marie.haglund@edu.sigtuna.se', 'shoj', 4, 1, 6);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (205, '2B', 2020, 20, 1, 260, shoj);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (260, 'Ida Maria', 'Rudin', 'ida.rudin@edu.sigtuna.se', 'shoj', 4, 1, 6);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (206, '2A', 2020, 26, 1, 261, satu);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (261, 'Nusin', 'Grama', 'nusin.grama@edu.sigtuna.se', 'satu', 4, 1, 6);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (207, '2B', 2020, 26, 1, 262, satu);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (262, 'Mona', 'Dirawi', 'mona.dirawi@edu.sigtuna.se', 'satu', 4, 1, 6);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (208, '2A', 2020, 21, 1, 263, ting);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (263, 'Linda', 'Lindroos', 'linda.lindroos@edu.sigtuna.se', 'ting', 4, 1, 6);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (209, '2B', 2020, 20, 1, 264, ting);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (264, 'Jessica', 'Sundberg', 'jessica.sundberg@edu.sigtuna.se', 'ting', 4, 1, 6);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (210, '2', 2020, 34, 1, NULL, vari);
INSERT INTO groups (`id`, `Name`, `Segment`, `StartYear`, `NumberStudents`, `Status`, `User_id`, `School_id`) VALUES (211, '2', 2020, NULL, 1, 265, jose);
INSERT INTO users (`id`, `FirstName`, `LastName`, `Mail`, `School_id`, `Role`, `Status`, `MessageSettings`) VALUES (265, 'Ewa', 'Andersson', 'ewa.andersson@josefinaskolan.nu', 'jose', 4, 1, 6);
